//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneratedBill
    {
        public int PayID { get; set; }
        public string FlatNumber { get; set; }
        public int BillID { get; set; }
        public Nullable<int> CurrentBillAmount { get; set; }
        public string CycleType { get; set; }
        public Nullable<System.DateTime> PaymentDueDate { get; set; }
        public Nullable<int> AmountTobePaid { get; set; }
        public Nullable<int> PreviousMonthBalance { get; set; }
        public Nullable<System.DateTime> AmountPaidDate { get; set; }
        public Nullable<int> AmountPaid { get; set; }
        public string PaymentMode { get; set; }
        public string TransactionID { get; set; }
        public string InvoiceID { get; set; }
        public Nullable<int> CurrentMonthBalance { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string BillDescription { get; set; }
        public Nullable<System.DateTime> BillStartDate { get; set; }
        public Nullable<System.DateTime> BillEndDate { get; set; }
        public System.DateTime BillMonth { get; set; }
        public int SocietyID { get; set; }
    }
}
