//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewUserSetting
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int TopicID { get; set; }
        public bool GCM { get; set; }
        public bool Mail { get; set; }
    }
}
