//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollingAnswer
    {
        public int ID { get; set; }
        public int PollID { get; set; }
        public int ResID { get; set; }
        public int SelectedAnswer { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public int SocietyID { get; set; }
    }
}
