//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentInventory
    {
        public int RentInventoryID { get; set; }
        public int InventoryID { get; set; }
        public int RentTypeID { get; set; }
        public int RentValue { get; set; }
        public Nullable<bool> Available { get; set; }
        public string Description { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public int UserID { get; set; }
        public int FlatID { get; set; }
    }
}
