//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Society
    {
        public int SocietyID { get; set; }
        public string ConnectionString { get; set; }
        public string SocietyName { get; set; }
        public int TotalFlats { get; set; }
        public string Sector { get; set; }
        public string City { get; set; }
        public Nullable<int> PinCode { get; set; }
    }
}
