//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Societybillplan
    {
        public int BillID { get; set; }
        public string BillType { get; set; }
        public string ChargeType { get; set; }
        public string Rate { get; set; }
        public string CycleType { get; set; }
        public int Applyto { get; set; }
        public int SocietyID { get; set; }
    }
}
