//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempResident
    {
        public int ResID { get; set; }
        public string FlatID { get; set; }
        public string FlatArea { get; set; }
        public int Floor { get; set; }
        public string Block { get; set; }
        public Nullable<int> IntercomNumber { get; set; }
        public string OwnerName { get; set; }
        public int BHK { get; set; }
        public string Type { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string MobileNoRes { get; set; }
        public string EmailIdRes { get; set; }
        public string Address { get; set; }
        public string UserLogin { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
    }
}
