//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclePoolEngagemment
    {
        public int PoolID { get; set; }
        public int VehiclePoolId { get; set; }
        public int InterestedResId { get; set; }
        public int Seats { get; set; }
        public int DealStatus { get; set; }
        public string Comments { get; set; }
    }
}
