//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPollCount
    {
        public int PollID { get; set; }
        public Nullable<int> Ans1 { get; set; }
        public Nullable<int> Ans2 { get; set; }
        public Nullable<int> Ans3 { get; set; }
        public Nullable<int> Ans4 { get; set; }
    }
}
