//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOwnerResident
    {
        public string FlatNumber { get; set; }
        public int UserID { get; set; }
        public int SocietyID { get; set; }
        public string FirstName { get; set; }
        public int Floor { get; set; }
        public string Block { get; set; }
        public Nullable<int> IntercomNumber { get; set; }
        public int BHK { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public Nullable<System.DateTime> DeActiveDate { get; set; }
    }
}
