//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewVisitorData
    {
        public int RequestId { get; set; }
        public int VisitorId { get; set; }
        public string VisitorName { get; set; }
        public string VisitorMobile { get; set; }
        public string VisitorAddress { get; set; }
        public byte[] VisitorImage { get; set; }
        public int ResId { get; set; }
        public string Flat { get; set; }
        public string VisitPurpose { get; set; }
        public System.DateTime ActualInTime { get; set; }
        public System.DateTime ActualOutTime { get; set; }
        public string SecurityCode { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> SocietyId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ResidentMobile { get; set; }
        public string Type { get; set; }
    }
}
