//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewForumNoImage
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FlatNumber { get; set; }
        public int ResID { get; set; }
        public int ThreadID { get; set; }
        public string Topic { get; set; }
        public string Thread { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
