//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFirstThreadwithCount
    {
        public int FirstID { get; set; }
        public int ThreadID { get; set; }
        public int ResID { get; set; }
        public string Topic { get; set; }
        public string FirstThread { get; set; }
        public System.DateTime InitiatedAt { get; set; }
        public Nullable<int> commentsCount { get; set; }
    }
}
