//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlatsBillPlan
    {
        public Nullable<int> FlatID { get; set; }
        public string FlatNumber { get; set; }
        public string FlatArea { get; set; }
        public Nullable<System.DateTime> FlatAddDate { get; set; }
        public Nullable<int> SocietyID { get; set; }
        public int SocietyBillID { get; set; }
        public int BillTypeID { get; set; }
        public string BillType { get; set; }
        public string ChargeType { get; set; }
        public string Rate { get; set; }
        public string CycleTYpe { get; set; }
        public int Applyto { get; set; }
        public System.DateTime BillPlanDate { get; set; }
    }
}
