//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewComplaintHistory
    {
        public int ID { get; set; }
        public int SocietyID { get; set; }
        public int CompID { get; set; }
        public int ResidentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Descrption { get; set; }
        public string CompStatus { get; set; }
        public string CompType { get; set; }
        public string Severity { get; set; }
        public string AssignedTo { get; set; }
        public System.DateTime ModifiedAt { get; set; }
    }
}
