//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewUserSetting
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string RegID { get; set; }
        public bool BillingNotification { get; set; }
        public bool BillingMail { get; set; }
        public bool BillingSMS { get; set; }
        public bool ComplaintNotification { get; set; }
        public bool ComplaintMail { get; set; }
        public bool ComplaintSMS { get; set; }
        public bool forumNotification { get; set; }
        public bool forumMail { get; set; }
        public bool forumSMS { get; set; }
        public bool NoticeNotification { get; set; }
        public bool NoticeMail { get; set; }
        public bool NoticeSMS { get; set; }
    }
}
