//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewComplaintLatest
    {
        public int SocietyID { get; set; }
        public int CompID { get; set; }
        public int Assignedto { get; set; }
        public string Descrption { get; set; }
        public int CurrentStatus { get; set; }
        public Nullable<System.DateTime> LastAt { get; set; }
    }
}
