//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewEmployeeAssignment
    {
        public int ResID { get; set; }
        public int UserID { get; set; }
        public int ServiceType { get; set; }
        public string CompType { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> DeActiveDate { get; set; }
        public Nullable<int> statusID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public string EmailId { get; set; }
        public int SocietyID { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public int AssignmentCount { get; set; }
    }
}
