//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlat
    {
        public int ID { get; set; }
        public string FlatNumber { get; set; }
        public int SocietyId { get; set; }
        public int BHK { get; set; }
        public int Floor { get; set; }
        public string Block { get; set; }
        public Nullable<int> IntercomNumber { get; set; }
        public string FlatArea { get; set; }
        public Nullable<int> OwnerUserID { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerMobile { get; set; }
        public string OwnerAddress { get; set; }
        public Nullable<int> TenantUserID { get; set; }
        public string TenantFirstName { get; set; }
        public string TenantLastName { get; set; }
        public string TenantEmail { get; set; }
        public string TenantMobile { get; set; }
        public string TenantAddress { get; set; }
        public Nullable<System.DateTime> TenantFrom { get; set; }
        public Nullable<System.DateTime> TenantTo { get; set; }
    }
}
