//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewVendor
    {
        public int VendorID { get; set; }
        public int ShopCategoryID { get; set; }
        public string ShopCategory { get; set; }
        public string VendorName { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public int SocietyID { get; set; }
        public string ContactNumber2 { get; set; }
        public string Address2 { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public int OfferID { get; set; }
        public string offer { get; set; }
        public System.DateTime OfferStartDate { get; set; }
        public System.DateTime OfferEndDate { get; set; }
        public System.DateTime OfferModifiedDate { get; set; }
    }
}
