//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewNewUserSetting
    {
        public int UserID { get; set; }
        public int ResID { get; set; }
        public int FlatID { get; set; }
        public int SocietyID { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string FirstName { get; set; }
        public string RegID { get; set; }
        public int TopicID { get; set; }
        public string Topic { get; set; }
        public int SettingID { get; set; }
        public bool GCM { get; set; }
        public bool Mail { get; set; }
    }
}
