//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRentInventory
    {
        public int RentInventoryID { get; set; }
        public int InventoryID { get; set; }
        public string Inventory { get; set; }
        public int RentTypeID { get; set; }
        public string RentType { get; set; }
        public int RentValue { get; set; }
        public Nullable<bool> Available { get; set; }
        public string Description { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public int UserID { get; set; }
        public int FlatID { get; set; }
        public string FlatNumber { get; set; }
        public Nullable<int> BHK { get; set; }
        public string FlatArea { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> SocietyID { get; set; }
        public string SocietyName { get; set; }
        public string sector { get; set; }
        public string FlatCity { get; set; }
        public Nullable<int> PinCode { get; set; }
        public string OwnerName { get; set; }
        public string MobileNo { get; set; }
        public int HouseID { get; set; }
        public string HouseNumber { get; set; }
    }
}
