//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApttSocietyAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorDetail
    {
        public int id { get; set; }
        public string VisitorMobileNo { get; set; }
        public string VisitorName { get; set; }
        public byte[] VisitorImage { get; set; }
        public string VisitorAddress { get; set; }
        public Nullable<int> SocietyId { get; set; }
    }
}
